name: macOS Build (AppleClang x86 & ARM)

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, arm64]
        build_type: [Release]
        shared: [ON, OFF]

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Configure CMake (macOS)
        run: >
          cmake -B build
          -DCMAKE_POLICY_VERSION_MINIMUM=3.5
          -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DPYRO_COMMON_SHARED_LIBRARY=${{ matrix.shared }}
          -DPYRO_PLATFORM_SHARED_LIBRARY=${{ matrix.shared }}
          -DPYRO_PLATFORM_DUMMY_INTERFACE=ON
          -DPYRO_RHI_BUILD_VULKAN=OFF
          -DPYRO_RHI_BUILD_DX12=OFF
          -DPYRO_RHI_BUILD_METAL=OFF
          -DSHOCKGRAPH_SHARED_LIBRARY=${{ matrix.shared }}
          -DSHOCKGRAPH_USE_PYRO_PLATFORM=ON
          -DSHOCKGRAPH_BUILD_VISUAL_TESTS=ON
          -DSHOCKGRAPH_BUILD_RENDERGRAPH_TESTS=ON
          -S .

      - name: Build (macOS)
        run: cmake --build build --config ${{ matrix.build_type }} --parallel 4

      - name: Run tests
        working-directory: build
        run: ctest --build-config ${{ matrix.build_type }}
